# Generated by Django 6.1.1 on 2026-09-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_security_constraints_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='social_comm_post_id_460cff_idx',
            old_name='social_comment_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='social_foll_followe_6a4bef_idx',
            old_name='social_follow_follower_following_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='social_foll_followi_f2e97e_idx',
            old_name='social_follow_following_follower_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='social_like_user_id_d8cf9b_idx',
            old_name='social_like_user_post_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='social_post_author__529923_idx',
            old_name='social_post_author_created_idx',
        ),
    ]
